// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/analytics/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna métricas consolidadas de scraping, produtos e alertas para o período.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Resumo analítico",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de dias (1-365, default 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Autentica com usuário e senha, retorna access_token JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credenciais",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "token_type": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/catalog": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna lista paginada de produtos do catálogo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Listar catálogo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número máximo de itens (default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset para paginação",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/snatcher_backendv2_internal_models.CatalogProduct"
                                    }
                                },
                                "limit": {
                                    "type": "integer"
                                },
                                "offset": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/catalog/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna um produto com suas variantes pelo ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Obter produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "product": {
                                    "$ref": "#/definitions/snatcher_backendv2_internal_models.CatalogProduct"
                                },
                                "variants": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/snatcher_backendv2_internal_models.CatalogVariant"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/channels": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um canal de notificação (WhatsApp/Telegram) com regras de alerta.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "Criar canal",
                "parameters": [
                    {
                        "description": "Dados do canal",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.channelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/snatcher_backendv2_internal_models.Channel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Verifica se o servidor está no ar.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/search-terms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todos os termos de busca cadastrados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search-terms"
                ],
                "summary": "Listar search terms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/snatcher_backendv2_internal_models.SearchTerm"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo termo de busca para scraping.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search-terms"
                ],
                "summary": "Criar search term",
                "parameters": [
                    {
                        "description": "Dados do search term",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.searchTermRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/snatcher_backendv2_internal_models.SearchTerm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handlers.channelRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "digest_max_items": {
                    "type": "integer"
                },
                "digest_mode": {
                    "type": "boolean"
                },
                "message_template": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "send_end_hour": {
                    "type": "integer"
                },
                "send_start_hour": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.searchTermRequest": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amz_tracking_id": {
                    "type": "string"
                },
                "crawl_interval": {
                    "type": "integer"
                },
                "max_val": {
                    "type": "number",
                    "minimum": 0
                },
                "min_val": {
                    "type": "number",
                    "minimum": 0
                },
                "ml_affiliate_tool_id": {
                    "type": "string"
                },
                "queries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "query": {
                    "type": "string",
                    "minLength": 2
                },
                "sources": {
                    "type": "string"
                }
            }
        },
        "snatcher_backendv2_internal_models.CatalogProduct": {
            "type": "object",
            "properties": {
                "brand": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "canonical_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "lowest_price": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullFloat64"
                },
                "lowest_price_source": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "lowest_price_url": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "tags": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                }
            }
        },
        "snatcher_backendv2_internal_models.CatalogVariant": {
            "type": "object",
            "properties": {
                "catalog_product_id": {
                    "type": "integer"
                },
                "first_seen_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "short_id": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "variant_label": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                }
            }
        },
        "snatcher_backendv2_internal_models.Channel": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "digest_max_items": {
                    "type": "integer"
                },
                "digest_mode": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "message_template": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "name": {
                    "type": "string"
                },
                "send_end_hour": {
                    "type": "integer"
                },
                "send_start_hour": {
                    "type": "integer"
                },
                "slug": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                }
            }
        },
        "snatcher_backendv2_internal_models.NullFloat64": {
            "type": "object",
            "properties": {
                "float64": {
                    "type": "number",
                    "format": "float64"
                },
                "valid": {
                    "description": "Valid is true if Float64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "snatcher_backendv2_internal_models.NullString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "snatcher_backendv2_internal_models.NullTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "snatcher_backendv2_internal_models.SearchTerm": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amz_tracking_id": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "crawl_interval": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_crawled_at": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullTime"
                },
                "max_val": {
                    "type": "number"
                },
                "min_val": {
                    "type": "number"
                },
                "ml_affiliate_tool_id": {
                    "$ref": "#/definitions/snatcher_backendv2_internal_models.NullString"
                },
                "queries": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "result_count": {
                    "type": "integer"
                },
                "sources": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Snatcher API",
	Description:      "API de scraping e monitoramento de preços com integração Telegram/WhatsApp.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
