import type { Config } from 'tailwindcss'
import animate from 'tailwindcss-animate'

export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: 'oklch(var(--bg) / <alpha-value>)',
        surface: 'oklch(var(--surface) / <alpha-value>)',
        'surface-2': 'oklch(var(--surface-2) / <alpha-value>)',
        'surface-3': 'oklch(var(--surface-3) / <alpha-value>)',
        border: 'oklch(var(--border) / <alpha-value>)',
        'border-strong': 'oklch(var(--border-strong) / <alpha-value>)',
        fg: 'oklch(var(--fg) / <alpha-value>)',
        'fg-2': 'oklch(var(--fg-2) / <alpha-value>)',
        'fg-3': 'oklch(var(--fg-3) / <alpha-value>)',
        'fg-4': 'oklch(var(--fg-4) / <alpha-value>)',
        accent: {
          DEFAULT: 'oklch(var(--accent) / <alpha-value>)',
          hover: 'oklch(var(--accent-hover) / <alpha-value>)',
          soft: 'oklch(var(--accent-soft) / <alpha-value>)',
        },
        success: 'oklch(var(--success) / <alpha-value>)',
        'success-soft': 'oklch(var(--success-soft) / <alpha-value>)',
        warning: 'oklch(var(--warning) / <alpha-value>)',
        'warning-soft': 'oklch(var(--warning-soft) / <alpha-value>)',
        danger: 'oklch(var(--danger) / <alpha-value>)',
        'danger-soft': 'oklch(var(--danger-soft) / <alpha-value>)',
        whatsapp: 'oklch(var(--whatsapp) / <alpha-value>)',
        // Legacy source badges — maintain temporarily for compatibility
        source: {
          0: { bg: '#EEF2FF', fg: '#3730A3' },
          1: { bg: '#F0FDF4', fg: '#15803D' },
          2: { bg: '#FDF2F8', fg: '#BE185D' },
          3: { bg: '#FEF3C7', fg: '#92400E' },
          4: { bg: '#DBEAFE', fg: '#0C4A6E' },
          5: { bg: '#F5F3FF', fg: '#5B21B6' },
          6: { bg: '#FEE2E2', fg: '#7C2D12' },
          7: { bg: '#E0E7FF', fg: '#1E1B4B' },
        },
      },
      spacing: {
        '4.5': '18px',
        '5.5': '22px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        base: 'var(--shadow)',
        lg: 'var(--shadow-lg)',
        card: 'var(--shadow)',
        modal: 'var(--shadow-lg)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['11.5px', { lineHeight: '1.4' }],
        xs: ['12.5px', { lineHeight: '1.4' }],
        sm: ['13.5px', { lineHeight: '1.5' }],
        base: ['14px', { lineHeight: '1.5' }],
        md: ['15px', { lineHeight: '1.5' }],
        lg: ['18px', { lineHeight: '1.4' }],
        xl: ['22px', { lineHeight: '1.3' }],
        '2xl': ['28px', { lineHeight: '1.2' }],
        '3xl': ['36px', { lineHeight: '1.1' }],
      },
      gap: {
        '0.5': 'var(--gap-1)',
        '1': 'var(--gap-2)',
        '1.5': 'var(--gap-3)',
        '2': 'var(--gap-4)',
        '2.5': 'var(--gap-5)',
        '3': 'var(--gap-6)',
        '4': 'var(--gap-8)',
      },
      padding: {
        'y': 'var(--pad-y)',
      },
    },
  },
  plugins: [animate],
} satisfies Config
