ALTER TABLE ads DROP COLUMN IF EXISTS client_name;
ALTER TABLE ads DROP COLUMN IF EXISTS paid_amount;
ALTER TABLE ads DROP COLUMN IF EXISTS short_id;
ALTER TABLE ads DROP COLUMN IF EXISTS click_count;
ALTER TABLE ads DROP COLUMN IF EXISTS target_url;
