// Centralizes all lucide-react icon re-exports used across the shell and nav.
// Import from here instead of directly from lucide-react to keep icon usage auditable.
export {
  LayoutDashboard,
  MessageSquare,
  FileText,
  BarChart3,
  Package,
  Tags,
  Layers,
  Send,
  Users,
  Link as LinkIcon,
  Smartphone,
  Globe,
  Network,
  Gauge,
  Activity,
  Shield,
  AlertTriangle,
  Brain,
  Eye,
  Settings,
  BookOpen,
  ChevronDown,
  ChevronRight,
  Menu,
  X,
} from 'lucide-react'
